name: opentelemetry
version: 0.18.1
description: A framework for collecting traces from applications.
homepage: https://github.com/Workiva/opentelemetry-dart
environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  async: '>=2.5.0 <3.0.0'
  collection: ^1.15.0
  fixnum: '>=1.0.0 <2.0.0'
  http: ">=0.13.0 <2.0.0"
  logging: ^1.0.0
  meta: '>=1.6.0 <2.0.0'
  protobuf: ">=2.0.0 <4.0.0"
  quiver: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.3
  build_test: ^2.2.1
  build_web_compilers: ">=3.2.7 <5.0.0"
  mockito: ^5.4.0
  remove_from_coverage: ^2.0.0
  test: ^1.24.2
  workiva_analysis_options: ^1.2.2

dependency_validator:
  ignore:
    - mockito
