name: opentelemetry
version: 0.3.0
description: A framework for collecting traces from applications.
homepage: https://github.com/Workiva/opentelemetry-dart
publish_to: https://pub.workiva.org
environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  fixnum: '>=0.10.0 <2.0.0'
  http: ^0.12.0
  logging: '>=0.11.4 <2.0.0'
  protobuf: '>=1.1.0 <3.0.0'

dev_dependencies:
  mockito: ^5.0.7
  test: ^1.16.5
  workiva_analysis_options: ^1.2.2
